// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using _2C2P___Aznar;

namespace webApi.Migrations
{
    [DbContext(typeof(RepositoryContext))]
    [Migration("20190905042243_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("_2C2P___Aznar.Models.Customer", b =>
                {
                    b.Property<long>("customerID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Mobile")
                        .IsRequired();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30);

                    b.HasKey("customerID");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            customerID = 1L,
                            Email = "user@domain.com",
                            Mobile = "0123456789",
                            Name = "Firstname Lastname"
                        },
                        new
                        {
                            customerID = 2L,
                            Email = "user2@domain.com",
                            Mobile = "111111111",
                            Name = "Firstname2 Lastname2"
                        },
                        new
                        {
                            customerID = 3L,
                            Email = "user3@domain.com",
                            Mobile = "222222222",
                            Name = "Firstname3 Lastname3"
                        });
                });

            modelBuilder.Entity("_2C2P___Aznar.Models.Transaction", b =>
                {
                    b.Property<long>("TransactionID")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DateTime");

                    b.Property<int>("Status");

                    b.Property<long?>("customerID");

                    b.HasKey("TransactionID");

                    b.HasIndex("customerID");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            TransactionID = 1L,
                            Amount = 1234.56m,
                            Currency = "USD",
                            Date = new DateTime(2018, 2, 28, 21, 34, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            customerID = 1L
                        },
                        new
                        {
                            TransactionID = 2L,
                            Amount = 2234.56m,
                            Currency = "THB",
                            Date = new DateTime(2018, 3, 28, 21, 34, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            customerID = 1L
                        },
                        new
                        {
                            TransactionID = 3L,
                            Amount = 12234.56m,
                            Currency = "SGD",
                            Date = new DateTime(2018, 4, 28, 21, 34, 0, 0, DateTimeKind.Unspecified),
                            Status = 0,
                            customerID = 1L
                        });
                });

            modelBuilder.Entity("_2C2P___Aznar.Models.Transaction", b =>
                {
                    b.HasOne("_2C2P___Aznar.Models.Customer", "Customer")
                        .WithMany("Transactions")
                        .HasForeignKey("customerID");
                });
#pragma warning restore 612, 618
        }
    }
}
